prefix: "&e[PhoBan] &f"
stage:
  available: "&aPhÃ²ng trá»‘ng"
  waiting: "&eÄang chá»"
  playing: "&bÄang chÆ¡i"
  ending: "&6Sáº¯p káº¿t thÃºc"
difficulty:
  easy: "&aDá»…"
  medium: "&eTrung BÃ¬nh"
  hard: "&cKhÃ³"
  extreme: "&5VÃ´ Cá»±c"
  challenge: "&4ğŸ’€ThÃ¡ch Äáº¥u"
already-joined: "&cBáº¡n Ä‘ang tham gia phÃ³ báº£n! &7Äá»ƒ thoÃ¡t, dÃ¹ng /phoban quit"
not-joined: "&cBáº¡n chÆ°a tham gia phÃ³ báº£n!"
not-in-waiting: "&cBáº¡n khÃ´ng thá»ƒ tham gia phÃ²ng nÃ y ngay bÃ¢y giá»!"
max-player-reached: "&cÄÃ£ Ä‘á»§ ngÆ°á»i! ({currentPlayers}/{maxPlayers})"
join-message: "&a&l[+] &f{player} ({currentPlayers}/{maxPlayers})"
leave-message: "&c&l[-] &f{player} ({currentPlayers}/{maxPlayers})"
waiting-cooldown: "&ePhÃ³ báº£n sáº½ báº¯t Ä‘áº§u sau {cooldown}s"
game-started: "&a&lPhÃ³ báº£n báº¯t Ä‘áº§u!"
ending-cooldown: "&ePhÃ³ báº£n sáº½ káº¿t thÃºc sau {cooldown}s"
kill-message: "&f&l{killer} Ä‘Ã£ giáº¿t {boss}"
respawn-cooldown: "&eBáº¡n sáº½ Ä‘Æ°á»£c há»“i sinh sau {cooldown}s"
respawn-max: "&cBáº¡n Ä‘Ã£ háº¿t lÆ°á»£t há»“i sinh. &7Äá»ƒ thoÃ¡t phÃ³ báº£n, dÃ¹ng /phoban quit"
win-message:
  - ""
  - "  &a&lVÆ¯á»¢T THÃ€NH CÃ”NG:&f&l PhÃ³ báº£n {dungeon}"
  - "  &eÄá»™ khÃ³: {difficulty} {challengeLevel}"
  - "  &eTá»• Ä‘á»™i: &f{currentPlayers}/{maxPlayers}"
  - "  &eThá»i gian hoÃ n thÃ nh: &f{completeTime}"
  - ""
loss-message:
  - ""
  - "  &c&lVÆ¯á»¢T THáº¤T Báº I:&f&l PhÃ³ báº£n {dungeon}"
  - "  &eÄá»™ khÃ³: {difficulty} {challengeLevel}"
  - "  &eTá»• Ä‘á»™i: &f{currentPlayers}/{maxPlayers}"
  - "  &eThá»i gian hoÃ n thÃ nh: &f{completeTime}"
  - ""
insufficient-ticket: "&cBáº¡n khÃ´ng cÃ³ Ä‘á»§ sá»‘ lÆ°á»£ng vÃ© yÃªu cáº§u!"
free-ticket-received: "&aBáº¡n nháº­n Ä‘Æ°á»£c &f{amount}&a vÃ© phÃ³ báº£n miá»…n phÃ­ hÃ ng ngÃ y!"
create-room-cooldown: "&cBáº¡n cÃ³ thá»ƒ táº¡o phÃ²ng má»›i sau {cooldown}!"
command-blocked: "&cBáº¡n khÃ´ng thá»ƒ dÃ¹ng lá»‡nh nÃ y trong phÃ³ báº£n. &7Äá»ƒ thoÃ¡t phÃ³ báº£n, dÃ¹ng /phoban quit"